version: "3.8"

services:
  web:
    build: .
    container_name: php-web-app
    ports:
      - "8080:80" # Mengakses web dari http://localhost:8080
    volumes:
      - ./src:/var/www/html # Direktori 'src' akan dihubungkan ke server web
    restart: always
